# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push: {}
  pull_request: {}

jobs:
  run:
    runs-on: ${{ matrix.macos }}
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: [15.3]
        include:
          - macos: macos-latest
            xcode: 15.3
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
